export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = " LOGIN_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = " LOAD_USER_FAIL";

export const LOGOUT = "LOGOUT";



//------------------POST-------------------

export const ADDPOST_SUCCESS = "ADDPOST_SUCCESS";
export const ADDPOST_FAIL = "ADDPOST_FAIL";

export const POSTDELETED_SUCCESS = "POSTDELETED_SUCCESS";
export const POSTDELETED_FAIL = "POSTDELETED_FAIL";

export const POSTUPDATED_SUCCESS = "POSTUPDATED_SUCCESS";
export const POSTUPDATED_FAIL = "POSTUPDATED_FAIL";


export const GETPOSTS = "GETPOSTS";
export const GET_POST = "GET_POST";
export const GETBYDATE = "GETBYDATE";



//------------COMMENT--------------------------------


export const ADDCOMMENT_SUCCESS = "AADCOMMENT_SUCCESS";
export const ADDCOOMENT_FAIL = "AADCOOMENT_FAIL";
export const GETCOMMENT_FAIL = "GETCOMMENTS_FAIL";
export const GETCOMMENT_SUCCESS = "GETCOMMENT_SUCCESS";
export const DELETECOMMENT_FAIL="DELETECOMMENT_FAIL";
export const DELETECOMMENT_SUSSESS="DELETECOMMENT_SUSSESS"
//---------------AADLIKE-----------------------


export const ADDLIKE_SUCCESS = "AADLIKE_SUCCESS";
export const ADDLIKE_FAIL = "AADLIKE_FAIL";

export const MOST_LIKED_POST = "MOST_LIKED_POST";
export const LIKEPOST_ERROR = "LIKEPOST_ERROR";

//--------------------USER----------------------



export const GET_USER_ERRORS = "  GET_USER_ERRORS";
export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAIL = "GETUSER_FAIL";
export const UPDATEUSER_SUCCES = "UPDATEUSER_SUCCES";
export const UPDATEUSER_FAIL = "UPDATEUSER_FAIL";
export const GETUSERS_SUCCESS = "GETUSERS_SUCCESS";
export const GETUSERS_FAIL = "GETUSERS_FAIL";


export const UNFOLLOW_FAIL = "UNFOLLOW_FAIL";
export const UNFOLLOW = "UNFOLLOW";
export const FOLLOW_FAIL = "FOLLOW_FAIL";
export const FOLLOW = "FOLLOW";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAIL = "SUBSCRIBE_FAIL";

export const GETFRIENDS_FAIL = "GETFRIENDS_FAIL";
export const GETFRIENDS_SUCCESS = "GETFRIENDS_SUCCESS";






//--------------GROUPE-------------------



export const CREATEGROUPE_SUCCESS = "CREATEGROUPE_SUCCESS";
export const CREATEGROUPE_FAIL = "CREATEGROUPE_FAIL";
export const GETGROUPE_SUCCESS = "GETGROUPE_SUCCESS";
export const GETGROUPE_FAIL = "GETGROUPE_FAIL";
export const UPDATEGROUPE_SUCCESS = "UPDATEGROUPE_SUCCESS";
export const UPDATEGROUPE_FAIL = "UPDATEGROUPE_FAIL";
export const GETGROUPES_FAIL = "GETGROUPES_FAIL";
export const GETGROUPES_SUCCESS = "GETGROUPES_SUCCESS";

export const GETGROUPEADMIN_SUCCESS = "GETGROUPEADMIN_SUCCESS";
export const GETGROUPEADMIN_FAIL = "GETGROUPEADMIN_FAIL";



export const ADDSUB_FAIL = "ADDSUB_FAIL";

export const ADDTOGROUPE_FAIL = "ADDTOGROUPE_FAIL";
export const ADDTOGROUPE_SUCCESS = "ADDTOGROUPE_SUCCESS";
export const REJECT_FAIL = "REJECT_FAIL";








